-- AUTO-GENERATO da data/cards.seed.json — rigenera con: node scripts/gen-seed.mjs
-- Re-seed: testi WOOH + colonna penalty (WOOH da bere se salti la carta)

alter table public.cards add column if not exists penalty int not null default 2;

insert into public.decks (slug, name, description, intensity, is_premium, min_players, sort_order) values
  ('start', $j${"it":"Start","en":"Start"}$j$::jsonb, $j${"it":"Per rompere il ghiaccio e scaldare il gruppo","en":"Break the ice and warm up the group"}$j$::jsonb, 1, false, 3, 1),
  ('mood', $j${"it":"Mood","en":"Mood"}$j$::jsonb, $j${"it":"Domande, sfide e risate di gruppo","en":"Questions, challenges and group laughs"}$j$::jsonb, 2, false, 3, 2),
  ('hot', $j${"it":"Hot","en":"Hot"}$j$::jsonb, $j${"it":"Piccante e imbarazzante. Solo per adulti","en":"Spicy and embarrassing. Adults only"}$j$::jsonb, 3, true, 3, 3),
  ('coppia', $j${"it":"Coppia","en":"Couple"}$j$::jsonb, $j${"it":"Pensato per giocare in due","en":"Designed to play as a duo"}$j$::jsonb, 2, true, 2, 4),
  ('ambiente', $j${"it":"Ambiente","en":"Surroundings"}$j$::jsonb, $j${"it":"Carte che interagiscono con il locale o la casa","en":"Cards that interact with the venue or home"}$j$::jsonb, 1, false, 3, 5)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  intensity = excluded.intensity,
  is_premium = excluded.is_premium,
  min_players = excluded.min_players,
  sort_order = excluded.sort_order;

delete from public.cards;
insert into public.cards (deck_id, type, text, param, is_persistent, needs_target, min_players, penalty, sort_order) values
  ((select id from public.decks where slug='start'), 'wooh', $j${"it":"Benvenuti a The WOOH Game! Se hai capito cos'è il WOOH, distribuisci 3 WOOH e tutti insieme urlate WOOH con il tono più assurdo che potete.","en":"Welcome to The WOOH Game! If you get what WOOH means, hand out 3 WOOH and everyone shouts WOOH in the most absurd tone possible."}$j$::jsonb, null, false, 0, 3, 1, 1),
  ((select id from public.decks where slug='start'), 'io_non_ho_mai', $j${"it":"Io non ho mai mandato un messaggio alla persona sbagliata. Chi l'ha fatto, beve.","en":"Never have I ever texted the wrong person. Whoever has, drinks."}$j$::jsonb, null, false, 0, 3, 1, 2),
  ((select id from public.decks where slug='start'), 'io_non_ho_mai', $j${"it":"Io non ho mai finto di aver capito una battuta che non avevo capito. Chi l'ha fatto, beve.","en":"Never have I ever pretended to get a joke I didn't get. Whoever has, drinks."}$j$::jsonb, null, false, 0, 3, 1, 3),
  ((select id from public.decks where slug='start'), 'io_non_ho_mai', $j${"it":"Io non ho mai cantato a squarciagola in macchina da solo. Chi l'ha fatto, beve.","en":"Never have I ever belted out a song alone in the car. Whoever has, drinks."}$j$::jsonb, null, false, 0, 3, 1, 4),
  ((select id from public.decks where slug='start'), 'tre_cose', $j${"it":"Di' 3 cose che hai nel telefono in questo momento e di cui un po' ti vergogni. Se non ne dici 3, bevi.","en":"Name 3 things in your phone right now that you're a little ashamed of. Can't name 3? Drink."}$j$::jsonb, null, false, 0, 3, 1, 5),
  ((select id from public.decks where slug='start'), 'tre_cose', $j${"it":"Le prime 3 cose che faresti se vincessi 10 milioni domani. Se non ne dici 3, bevi.","en":"The first 3 things you'd do if you won 10 million tomorrow. Can't name 3? Drink."}$j$::jsonb, null, false, 0, 3, 1, 6),
  ((select id from public.decks where slug='start'), 'sinonimi', $j${"it":"A turno, dite un sinonimo di \"essere ubriaco\". Il primo che non sa cosa dire, beve.","en":"Take turns saying a synonym for \"being drunk\". First one stuck, drinks."}$j$::jsonb, $j${"tema":{"it":"essere ubriaco","en":"being drunk"}}$j$::jsonb, false, 0, 3, 1, 7),
  ((select id from public.decks where slug='start'), 'sinonimi', $j${"it":"A turno, dite un sinonimo di \"soldi\". Il primo che non sa cosa dire, beve.","en":"Take turns saying a synonym for \"money\". First one stuck, drinks."}$j$::jsonb, $j${"tema":{"it":"soldi","en":"money"}}$j$::jsonb, false, 0, 3, 1, 8),
  ((select id from public.decks where slug='start'), 'azione', $j${"it":"Fai un complimento sincero a {player}. Se ti viene da ridere, bevi.","en":"Give {player} a sincere compliment. If you laugh, you drink."}$j$::jsonb, null, false, 1, 3, 1, 9),
  ((select id from public.decks where slug='start'), 'azione', $j${"it":"Imita {player} finché gli altri non indovinano chi è. Se non ci riesci, bevi.","en":"Imitate {player} until the others guess who it is. Fail and you drink."}$j$::jsonb, null, false, 1, 3, 1, 10),
  ((select id from public.decks where slug='start'), 'regola', $j${"it":"REGOLA: fino alla prossima regola, nessuno può chiamare gli altri per nome. Chi sbaglia, beve.","en":"RULE: until the next rule, no one may call others by name. Slip up, drink."}$j$::jsonb, null, true, 0, 3, 1, 11),
  ((select id from public.decks where slug='start'), 'regola', $j${"it":"REGOLA: fino alla prossima regola, ogni volta che qualcuno dice \"sì\" beve un WOOH.","en":"RULE: until the next rule, every time someone says \"yes\" they take a WOOH."}$j$::jsonb, null, true, 0, 3, 1, 12),
  ((select id from public.decks where slug='mood'), 'wooh', $j${"it":"Momento WOOH: l'ultimo che alza le mani e urla WOOH distribuisce 2 WOOH.","en":"WOOH moment: the last to raise their hands and shout WOOH hands out 2 WOOH."}$j$::jsonb, null, false, 0, 3, 2, 1),
  ((select id from public.decks where slug='mood'), 'io_non_ho_mai', $j${"it":"Io non ho mai mentito sulla mia età. Chi l'ha fatto, beve.","en":"Never have I ever lied about my age. Whoever has, drinks."}$j$::jsonb, null, false, 0, 3, 2, 2),
  ((select id from public.decks where slug='mood'), 'io_non_ho_mai', $j${"it":"Io non ho mai stalkerato l'ex di qualcuno sui social. Chi l'ha fatto, beve.","en":"Never have I ever stalked someone's ex on social media. Whoever has, drinks."}$j$::jsonb, null, false, 0, 3, 2, 3),
  ((select id from public.decks where slug='mood'), 'tre_cose', $j${"it":"Le prime 3 cose che faresti se per un giorno cambiassi genere. Se non ne dici 3, bevi.","en":"The first 3 things you'd do if you swapped gender for a day. Can't name 3? Drink."}$j$::jsonb, null, false, 0, 3, 2, 4),
  ((select id from public.decks where slug='mood'), 'tre_cose', $j${"it":"Di' 3 persone in questa stanza con cui andresti su un'isola deserta. Se non ne dici 3, bevi.","en":"Name 3 people in this room you'd take to a desert island. Can't name 3? Drink."}$j$::jsonb, null, false, 0, 3, 2, 5),
  ((select id from public.decks where slug='mood'), 'sinonimi', $j${"it":"A turno, dite un sinonimo di \"fumare\". Il primo che non sa cosa dire, beve.","en":"Take turns saying a synonym for \"smoking\". First one stuck, drinks."}$j$::jsonb, $j${"tema":{"it":"fumare","en":"smoking"}}$j$::jsonb, false, 0, 3, 2, 6),
  ((select id from public.decks where slug='mood'), 'azione', $j${"it":"Guarda {player} negli occhi per 10 secondi senza ridere. Se ridi, bevi.","en":"Look {player} in the eyes for 10 seconds without laughing. Laugh and you drink."}$j$::jsonb, null, false, 1, 3, 2, 7),
  ((select id from public.decks where slug='mood'), 'azione', $j${"it":"Lascia che {player} scriva un messaggio dal tuo telefono all'ultima persona con cui hai chattato. Se rifiuti, bevi 3 WOOH.","en":"Let {player} send a message from your phone to the last person you chatted with. Refuse and drink 3."}$j$::jsonb, null, false, 1, 3, 2, 8),
  ((select id from public.decks where slug='mood'), 'regola', $j${"it":"REGOLA: fino alla prossima regola, si può bere solo con la mano sinistra. Chi usa la destra, beve.","en":"RULE: until the next rule, drink only with your left hand. Use your right, drink."}$j$::jsonb, null, true, 0, 3, 2, 9),
  ((select id from public.decks where slug='mood'), 'regola', $j${"it":"REGOLA: nominate un \"capitano\". Quando lui beve, bevono tutti. Vale fino alla prossima regola.","en":"RULE: pick a \"captain\". When they drink, everyone drinks. Until the next rule."}$j$::jsonb, null, true, 0, 3, 2, 10),
  ((select id from public.decks where slug='hot'), 'wooh', $j${"it":"WOOH bollente: chi ha il look più hot stasera distribuisce 3 WOOH. Decide il gruppo.","en":"Spicy WOOH: whoever looks hottest tonight hands out 3 WOOH. The group decides."}$j$::jsonb, null, false, 0, 3, 3, 1),
  ((select id from public.decks where slug='hot'), 'io_non_ho_mai', $j${"it":"Io non ho mai baciato qualcuno la prima sera in cui l'ho conosciuto. Chi l'ha fatto, beve.","en":"Never have I ever kissed someone the first night I met them. Whoever has, drinks."}$j$::jsonb, null, false, 0, 3, 3, 2),
  ((select id from public.decks where slug='hot'), 'io_non_ho_mai', $j${"it":"Io non ho mai avuto una cotta per un amico o un'amica presente stasera. Chi l'ha fatto, beve.","en":"Never have I ever had a crush on a friend who's here tonight. Whoever has, drinks."}$j$::jsonb, null, false, 0, 3, 3, 3),
  ((select id from public.decks where slug='hot'), 'tre_cose', $j${"it":"Di' 3 cose che trovi irresistibili in una persona. Se non ne dici 3, bevi.","en":"Name 3 things you find irresistible in a person. Can't name 3? Drink."}$j$::jsonb, null, false, 0, 3, 3, 4),
  ((select id from public.decks where slug='hot'), 'azione', $j${"it":"Sussurra all'orecchio di {player} la cosa più audace che ti viene in mente. Se non lo fai, bevi 3 WOOH.","en":"Whisper the boldest thing you can think of in {player}'s ear. Don't, and drink 3."}$j$::jsonb, null, false, 1, 3, 3, 5),
  ((select id from public.decks where slug='hot'), 'azione', $j${"it":"Fai un massaggio alle spalle a {player} per 20 secondi. Se rifiuti, bevi.","en":"Give {player} a 20-second shoulder massage. Refuse and you drink."}$j$::jsonb, null, false, 1, 3, 3, 6),
  ((select id from public.decks where slug='hot'), 'azione', $j${"it":"Mima con {player} la posa di coppia più teatrale e hot che riesci a inventare. Più è esagerata, meglio è.","en":"Strike the most theatrical, over-the-top couple pose with {player} you can invent. The bigger, the better."}$j$::jsonb, null, false, 1, 3, 3, 7),
  ((select id from public.decks where slug='hot'), 'manichino', $j${"it":"{player}, prendi {player2}: è il tuo manichino. Puoi mettergli le braccia in pose buffe finché non esce un'altra regola.","en":"{player}, take {player2}: they're your mannequin. Pose their arms however you like until the next rule."}$j$::jsonb, null, true, 2, 4, 3, 8),
  ((select id from public.decks where slug='hot'), 'regola', $j${"it":"REGOLA: fino alla prossima regola, ogni volta che qualcuno ride deve fare un complimento piccante a chi ha di fianco.","en":"RULE: until the next rule, anyone who laughs must give a spicy compliment to the person next to them."}$j$::jsonb, null, true, 0, 3, 3, 9),
  ((select id from public.decks where slug='coppia'), 'wooh', $j${"it":"Momento WOOH di coppia: contate insieme 3, 2, 1 e urlate WOOH. Chi parte in ritardo, beve.","en":"Couple WOOH moment: count 3, 2, 1 together and shout WOOH. Whoever's late, drinks."}$j$::jsonb, null, false, 0, 2, 2, 1),
  ((select id from public.decks where slug='coppia'), 'io_non_ho_mai', $j${"it":"Io non ho mai pensato a te durante una canzone. Se è falso, bevi.","en":"Never have I ever thought of you during a song. If that's a lie, drink."}$j$::jsonb, null, false, 0, 2, 2, 2),
  ((select id from public.decks where slug='coppia'), 'tre_cose', $j${"it":"Di' 3 cose che ti piacciono dell'altra persona e che non le hai mai detto. Se non ne dici 3, bevi.","en":"Name 3 things you like about the other person you've never told them. Can't name 3? Drink."}$j$::jsonb, null, false, 0, 2, 2, 3),
  ((select id from public.decks where slug='coppia'), 'azione', $j${"it":"Guarda {player} negli occhi per 30 secondi senza parlare. Chi distoglie lo sguardo per primo, beve.","en":"Stare into {player}'s eyes for 30 seconds in silence. First to look away, drinks."}$j$::jsonb, null, false, 1, 2, 2, 4),
  ((select id from public.decks where slug='coppia'), 'azione', $j${"it":"Dai un bacio sulla guancia o sul collo a {player}, scegli tu dove. Se non lo fai, bevi 2 WOOH.","en":"Give {player} a kiss on the cheek or neck, your choice. Don't, and drink 2."}$j$::jsonb, null, false, 1, 2, 2, 5),
  ((select id from public.decks where slug='coppia'), 'regola', $j${"it":"REGOLA: fino alla prossima regola dovete restare con le mani intrecciate. Chi si stacca, beve.","en":"RULE: until the next rule you must keep your hands intertwined. Let go, and drink."}$j$::jsonb, null, true, 0, 2, 2, 6),
  ((select id from public.decks where slug='ambiente'), 'wooh', $j${"it":"WOOH ambientale: il primo che trova qualcosa di giallo nella stanza e lo alza urlando WOOH distribuisce 2 WOOH.","en":"Surroundings WOOH: first to find something yellow in the room and raise it shouting WOOH hands out 2 WOOH."}$j$::jsonb, null, false, 0, 3, 1, 1),
  ((select id from public.decks where slug='ambiente'), 'azione', $j${"it":"L'ultimo che tocca il pavimento beve. Via!","en":"Last one to touch the floor drinks. Go!"}$j$::jsonb, null, false, 0, 3, 1, 2),
  ((select id from public.decks where slug='ambiente'), 'azione', $j${"it":"Il primo che porta un oggetto rosso al centro del tavolo distribuisce 2 WOOH.","en":"First to bring a red object to the center of the table hands out 2 WOOH."}$j$::jsonb, null, false, 0, 3, 1, 3),
  ((select id from public.decks where slug='ambiente'), 'azione', $j${"it":"Chi ha lo schermo del telefono più rovinato beve. Mostratelo tutti.","en":"Whoever has the most cracked phone screen drinks. Everyone show it."}$j$::jsonb, null, false, 0, 3, 1, 4),
  ((select id from public.decks where slug='ambiente'), 'regola', $j${"it":"REGOLA: fino alla prossima regola, chi appoggia il bicchiere senza usare un sottobicchiere (o un oggetto al posto suo) beve.","en":"RULE: until the next rule, anyone who sets their glass down without a coaster (or a stand-in) drinks."}$j$::jsonb, null, true, 0, 3, 1, 5),
  ((select id from public.decks where slug='ambiente'), 'sinonimi', $j${"it":"A turno, dite una cosa che si trova in cucina. Il primo che non sa cosa dire, beve.","en":"Take turns naming something found in a kitchen. First one stuck, drinks."}$j$::jsonb, $j${"tema":{"it":"cose che si trovano in cucina","en":"things found in a kitchen"}}$j$::jsonb, false, 0, 3, 1, 6);
